version: '3.6'

services:
  control:
    build: ./control
    hostname: control
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./ansible
        target: /var/ansible

  lb01:
    build: ./base
    hostname: lb01
    stdin_open: true
    tty: true
    restart: always

  app01:
    build: ./base
    hostname: app01
    stdin_open: true
    tty: true
    restart: always

  app02:
    build: ./base
    hostname: app02
    stdin_open: true
    tty: true
    restart: always

  db01:
    build: ./base
    hostname: db01
    stdin_open: true
    tty: true
    restart: always
    ports:
    - "3306:3306"
