---
- hosts: database
  tasks:
    - name: install mysql server
      apt:
        name:
          - mysql-server
        state: present
        update_cache: yes
    - name: install tools
      apt:
        name:
          - mysql-client
          - python3-mysqldb
          - libmysqlclient-dev
        state: present
    - name: install vim tools
      apt:
        name:
          - vim
        state: present
        update_cache: yes
    - name: ensure mysql listening on all ports
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: ^bind-address
        line: "bind-address = 0.0.0.0"
      notify: restart mysql
    - name: ensure mysql started
      become: true
      ansible.builtin.service: name=mysql state=restarted enabled=true
    - name: create demo database
      mysql_db:
        name: demo
        state: present
    - name: create demo user
      mysql_user:
        name: demo
        password: demo
        priv: "demo.*:ALL"
        host: "%"
        state: present
  handlers:
    - name: restart mysql
      ansible.builtin.service: name=mysql state=restarted enabled=true
