---
- hosts: webserver
  become: true
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
    - name: Create linux user
      user:
        name: usera
        comment: Node User
        state: present
        group: adm
    - name: copy demo app source
      copy:
        src: node-hello/
        dest: /var/www/node-hello
        mode: 0755
    - name: install dependencies
      npm:
        path: /var/www/node-hello
    - name: start the node application
      command:
        chdir: /var/www/node-hello
        cmd: node index.js
      async: 1000
      poll: 0
